version: '3.9'

services:
  mysql:
    image: mysql:8.3
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: sys_operation
    command:
      - --default-authentication-plugin=mysql_native_password
      - --log-error-verbosity=1
      - --character-set-server=utf8mb4
      - --collation-server=utf8mb4_unicode_ci
      - --innodb_lock_wait_timeout=1
    ports:
      - "3306:3306"
    deploy:
      resources:
        limits:
          cpus: "0.5"
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      interval: 10s
      timeout: 5s
      retries: 5

  redis:
    image: redis:7
    ports:
      - "6379:6379"
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 10s
      timeout: 5s
      retries: 5

  workforcehub:
    image: alpine:latest
    ports:
      - "8020:8020"
    volumes:
      - ./workforcehub:/workforcehub
    working_dir: /test
    command: "sh runserver.sh"
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy