# Generated by Django 4.2.14 on 2024-12-03 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Employee', max_length=100),
        ),
    ]
