# Generated by Django 4.2.14 on 2024-12-11 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address',
            field=models.CharField(default='No address provided', max_length=255),
        ),
        migrations.AddField(
            model_name='user',
            name='bonus',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='department',
            field=models.CharField(default='None', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='education_and_certifications',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email_id',
            field=models.CharField(default='noemail@example.com', max_length=500),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_name',
            field=models.CharField(default='N/A', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(default='000-0000-0000', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='employment_status',
            field=models.CharField(choices=[('Active', 'Active'), ('On Leave', 'On Leave'), ('Resigned', 'Resigned')], default='Active', max_length=20),
        ),
        migrations.AddField(
            model_name='user',
            name='hire_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='Unknown', max_length=50),
        ),
        migrations.AddField(
            model_name='user',
            name='performance_review',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='phone_number',
            field=models.CharField(default='000-0000-0000', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='employee_photos/'),
        ),
        migrations.AddField(
            model_name='user',
            name='position',
            field=models.CharField(default='Employee', max_length=100),
        ),
        migrations.AddField(
            model_name='user',
            name='resignation_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='user',
            name='skills',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='vacation_days',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='user',
            name='work_experience',
            field=models.TextField(blank=True, null=True),
        ),
    ]
