# Generated by Django 4.2.14 on 2024-12-11 23:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_user_address_user_bonus_user_date_of_birth_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email_id',
            field=models.CharField(max_length=500),
        ),
        migrations.AlterField(
            model_name='user',
            name='emergency_contact_phone',
            field=models.CharField(max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='nationality',
            field=models.CharField(default='korea', max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=100),
        ),
    ]
