# Generated by Django 4.2.14 on 2024-12-08 21:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0002_user_position'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='password',
        ),
    ]
