# Generated by Django 4.2.14 on 2024-12-14 12:15

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0003_alter_user_email_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='performance_review',
        ),
        migrations.RemoveField(
            model_name='user',
            name='skills',
        ),
        migrations.AlterField(
            model_name='user',
            name='hire_date',
            field=models.DateField(default=datetime.date.today, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='salary',
            field=models.DecimalField(decimal_places=2, default=3000, max_digits=10),
        ),
        migrations.AlterField(
            model_name='user',
            name='vacation_days',
            field=models.IntegerField(default='12'),
        ),
    ]
