# Generated by Django 4.2.14 on 2024-12-16 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0004_remove_user_performance_review_remove_user_skills_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission',
            field=models.TextField(default=False),
        ),
    ]
