# Generated by Django 4.2.14 on 2024-12-16 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0005_user_permission'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='permission_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
