# Generated by Django 4.2.14 on 2024-12-16 21:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0006_user_permission_date'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='permission_date',
            new_name='approval_date',
        ),
    ]
