# Generated by Django 4.2.14 on 2025-02-22 02:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('personal_data', '0008_alter_user_emergency_contact_phone_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
