# Generated by Django 4.2.14 on 2024-10-17 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=255)),
            ],
            options={
                'db_table': 'permission',
            },
        ),
    ]
