# Generated by Django 4.2.14 on 2024-10-17 12:01

from django.db import migrations

# python manage.py makemigrations permissions --empty --name add_initial_data
def create_sample_data(apps, schema_editor):
	Item = apps.get_model('permissions', 'Permission')
	Item.objects.bulk_create([
		Item(code='question', name= '질문 권한', description='질문을 할 수 있는 권한입니다.'),
		Item(code='answer', name= '답변 권한', description='답변을 할 수 있는 권한입니다.'),
		Item(code='open_class', name= '수업_개설 권한', description='수업_개설을 할 수 있는 권한입니다.'),
		Item(code='delete_class', name= '수업_삭제 권한', description='수업_삭제을 할 수 있는 권한입니다.'),
		Item(code='update_class', name= '수업_수정 권한', description='수업_수정을 할 수 있는 권한입니다.'),
	])

class Migration(migrations.Migration):

	dependencies = [
		('permissions', '0001_initial'),
	]

	operations = [
		migrations.RunPython(create_sample_data),
	]