# Generated by Django 4.2.14 on 2025-02-23 08:50

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='pw_changed_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
