# Generated by Django 4.2.14 on 2025-02-23 08:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_alter_passwordhistory_pw_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='pw_changed_at',
            field=models.DateTimeField(default=datetime.datetime(2025, 2, 23, 8, 54, 56, 318701, tzinfo=datetime.timezone.utc)),
        ),
    ]
