# Generated by Django 4.2.14 on 2025-02-23 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_passwordhistory_pw_changed_at'),
    ]

    operations = [
        migrations.AlterField(
            model_name='passwordhistory',
            name='pw_changed_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
