# Generated by Django 4.2.14 on 2024-12-17 23:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_action', '0003_file_description_file_file_type_file_is_encrypted_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=100)),
                ('profile_picture', models.FileField(upload_to='profile_pictures/')),
            ],
        ),
        migrations.DeleteModel(
            name='File',
        ),
    ]
