# Generated by Django 4.2.14 on 2025-01-11 12:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_action', '0005_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Board',
        ),
    ]
