# Generated by Django 4.2.14 on 2025-01-14 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_action', '0008_passwordhistory_delete_customuser'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='notice',
            table=None,
        ),
    ]
