# Generated by Django 4.2.14 on 2025-02-16 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operation_action', '0011_rename_email_message_receiver_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='is_read',
            field=models.BooleanField(default=False),
        ),
    ]
