# Generated by Django 4.2.14 on 2025-02-21 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_action', '0013_alter_notice_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Notice',
        ),
    ]
