# Generated by Django 4.2.14 on 2025-02-23 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_action', '0014_delete_notice'),
    ]

    operations = [
        migrations.DeleteModel(
            name='PasswordHistory',
        ),
    ]
