# Generated by Django 4.2.14 on 2025-02-24 01:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('operation_action', '0015_delete_passwordhistory'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserProfile',
        ),
    ]
