# Generated by Django 4.2.14 on 2024-10-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        ('permissions', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=31, unique=True)),
                ('name', models.CharField(max_length=127)),
                ('description', models.CharField(max_length=255)),
                ('permissions', models.ManyToManyField(related_name='roles', to='permissions.permission')),
                ('users', models.ManyToManyField(related_name='roles', to='users.user')),
            ],
            options={
                'db_table': 'role',
            },
        ),
    ]
