# Generated by Django 4.2.14 on 2024-10-17 11:45

# python manage.py makemigrations roles --empty --name add_initial_data
from django.db import migrations

def create_sample_data(apps, schema_editor):
    Item = apps.get_model('roles', 'Role')
    Item.objects.bulk_create([
        Item(code='student',name = '학생', description='학생에게 부여되는 역할입니다.'),
        Item(code='teacher',name = '강사', description='강사에게 부여되는 역할입니다.'),
    ])

class Migration(migrations.Migration):

    dependencies = [
        ('roles', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_sample_data),
    ]
